/** Type of a soundfile containing all relevant information */
export type SoundFile = {src: string, title: string, duration?: number, artist?: string, url?: string};

/** An array of all available music files. */
export const MusicFiles: Array<SoundFile & {duration: number}> = [
  { artist: 'Ron Gelinas Chillout Lounge', duration: 223.25, src: 'Acceptance.mp3', title: 'Acceptance', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 210, src: 'All_in_a_Day.mp3', title: 'All in a Day', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 168.5, src: 'Another_Day.mp3', title: 'Another Day', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 158.25, src: 'Aura.mp3', title: 'Aura', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 220.75, src: 'Beacon_Of_Light.mp3', title: 'Beacon Of Light', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 190, src: 'Believe.mp3', title: 'Believe', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 186.5, src: 'Best_Wishes.mp3', title: 'Best Wishes', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 211.25, src: 'Break_Away.mp3', title: 'Break Away', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 127.06, src: 'Campfire.mp3', title: 'Campfire', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 160.41, src: 'Carefree.mp3', title: 'Carefree', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 162.44, src: 'Casual.mp3', title: 'Casual', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 131.71, src: 'Cleansing_Rain.mp3', title: 'Cleansing Rain', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 4.39, src: 'Come.mp3', title: 'Come', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 57.27, src: 'Connecting.mp3', title: 'Connecting', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 2.18, src: 'Contentment.mp3', title: 'Contentment', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 19.59, src: 'Daybreak_Chill_Blend.mp3', title: 'Daybreak Chill Blend', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 27.00, src: 'Defiant.mp3', title: 'Defiant', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 19.20, src: 'Desires.mp3', title: 'Desires', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 11.05, src: 'Drops.mp3', title: 'Drops', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 1 * 60 + 44.68, src: 'Easy.mp3', title: 'Easy', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 57.00, src: 'Edge_Of_Night.mp3', title: 'Edge Of Night', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 53.82, src: 'Elegantly_Disconnected.mp3', title: 'Elegantly Disconnected', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 16.24, src: 'Endeavour.mp3', title: 'Endeavour', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 55.25, src: 'Equanimity.mp3', title: 'Equanimity', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 8.57, src: 'Equatorial_Run.mp3', title: 'Equatorial Run', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 42.00, src: 'Equilibrium.mp3', title: 'Equilibrium', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 2.61, src: 'Equinox.mp3', title: 'Equinox', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 7.50, src: 'Evening_Out.mp3', title: 'Evening Out', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 37.71, src: 'Falling_Leaves.mp3', title: 'Falling Leaves', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 58.96, src: 'Far_Away.mp3', title: 'Far Away', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 39.13, src: 'Feel_It.mp3', title: 'Feel It', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 40.41, src: 'Feeling_Good.mp3', title: 'Feeling Good', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 2.96, src: 'Feeling_Lucky.mp3', title: 'Feeling Lucky', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 44.35, src: 'Fulfilled.mp3', title: 'Fulfilled', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 1.09, src: 'Gaining_Momentum.mp3', title: 'Gaining Momentum', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 6.82, src: 'Get_Over_It.mp3', title: 'Get Over It', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 39.57, src: 'Getting_It_Done.mp3', title: 'Getting It Done', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 47.88, src: 'Hang_Gliding.mp3', title: 'Hang Gliding', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 16.36, src: 'Happy_Place.mp3', title: 'Happy Place', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 4 * 60 + 6.15, src: 'Here.mp3', title: 'Here', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 27.69, src: 'Iced_Tea.mp3', title: 'Iced Tea', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 27.50, src: 'Imminent.mp3', title: 'Imminent', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 35.56, src: 'Island_Hopping.mp3', title: 'Island Hopping', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 33.91, src: 'Island_Life.mp3', title: 'Island Life', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 48.51, src: 'It_Is_What_It_Is.mp3', title: 'It Is What It Is', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 49.09, src: 'Let_It_Go_Now.mp3', title: 'Let It Go Now', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 37.96, src: 'Loyal.mp3', title: 'Loyal', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 2.55, src: 'Midnight_Shuffle.mp3', title: 'Midnight Shuffle', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 16.36, src: 'Mojito.mp3', title: 'Mojito', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 7.59, src: 'Monday_Morning.mp3', title: 'Monday Morning', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 4 * 60 + 5.94, src: 'Natural_High.mp3', title: 'Natural High', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 13.09, src: 'Never_Meant_To_Be.mp3', title: 'Never Meant To Be', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 14.40, src: 'New_Direction_Instrumental.mp3', title: 'New Direction Instrumental', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 34.74, src: 'New_Heights.mp3', title: 'New Heights', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 34.11, src: 'Night_At_The_Beach.mp3', title: 'Night At The Beach', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 50.40, src: 'Over_The_Horizon.mp3', title: 'Over The Horizon', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 25.12, src: 'Peculiar.mp3', title: 'Peculiar', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 35.71, src: 'Ready.mp3', title: 'Ready', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 3.00, src: 'Remember.mp3', title: 'Remember', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 59.08, src: 'Reminiscence.mp3', title: 'Reminiscence', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 40.80, src: 'Resolve_Clean_Guitar.mp3', title: 'Resolve Clean Guitar', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 40.80, src: 'Resolve_Gritty_Guitar.mp3', title: 'Resolve Gritty Guitar', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 19.09, src: 'Simplify.mp3', title: 'Simplify', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 55.61, src: 'Slinky.mp3', title: 'Slinky', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 8.57, src: 'Slow_Grind.mp3', title: 'Slow Grind', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 23.18, src: 'Soul_Searching.mp3', title: 'Soul Searching', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 30.61, src: 'Soulful_Memories.mp3', title: 'Soulful Memories', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 57.50, src: 'Still_Standing.mp3', title: 'Still Standing', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 38.18, src: 'Subtle_Swagger.mp3', title: 'Subtle Swagger', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 46.00, src: 'Summer.mp3', title: 'Summer', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 41.12, src: 'The_Art_of_Healing.mp3', title: 'The Art of Healing', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 37.33, src: 'The_City.mp3', title: 'The City', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 57.14, src: 'Thinking_of_You.mp3', title: 'Thinking of You', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 14.32, src: 'Tropical_Yearnings.mp3', title: 'Tropical Yearnings', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 34.67, src: 'Upside_Quest.mp3', title: 'Upside Quest', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 52.00, src: 'Urgent.mp3', title: 'Urgent', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 4.19, src: 'Voyage.mp3', title: 'Voyage', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 1.28, src: 'Waiting.mp3', title: 'Waiting', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 11.71, src: 'Wandering.mp3', title: 'Wandering', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 12.00, src: 'We_Are_Harmony.mp3', title: 'We Are Harmony', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 5.16, src: 'Where_Will_I_Go_Instrumental.mp3', title: 'Where Will I Go? Instrumental', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 25.00, src: 'Windsurfing.mp3', title: 'Windsurfing', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 51.43, src: 'Winter_Bounce.mp3', title: 'Winter Bounce', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 21.33, src: 'You.mp3', title: 'You', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 0.00, src: 'You_Show_Me_Remix.mp3', title: 'You Show Me Remix', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 54.86, src: 'You_Show_Me_feat._Kellie_Allen.mp3', title: 'You Show Me feat. Kellie Allen', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
];

/** Total duration of the music in seconds */
export const TotalMusicDuration = MusicFiles.reduce((prev, curr) => prev + curr.duration, 0);

export const Sounds: Array<SoundFile> = [
  { src: 'campfire.mp3', title: 'Campfire' },
  { src: 'people_talk_inside.mp3', title: 'People talk inside' },
  { src: 'rain_city.mp3', title: 'Rain City' },
  { src: 'rain_forest.mp3', title: 'Rain Forest' },
  { src: 'river.mp3', title: 'River' },
  { src: 'waves.mp3', title: 'Waves' },
  { src: 'wind.mp3', title: 'Wind' },
];

export type LottieSrc = { src: string, needsFullscreen: boolean, alignment: 'top' | 'center' | 'bottom', bottomColor: string, topColor: string, backgroundColor?: string };

export const Lotties: Array<LottieSrc> = [
  { alignment: 'center', backgroundColor: '#111', bottomColor: '#FFF', needsFullscreen: false, src: 'mushroom.json', topColor: '#FFF' },
  { alignment: 'center', backgroundColor: '#000', bottomColor: '#FFF', needsFullscreen: false, src: 'l1.json', topColor: '#FFF' },
  { alignment: 'center', backgroundColor: '#65f0f7', bottomColor: '#222', needsFullscreen: false, src: 'turtle.json', topColor: '#222' },
  { alignment: 'center', backgroundColor: '#000', bottomColor: '#FFF', needsFullscreen: false, src: 'globe.json', topColor: '#FFF' },
  { alignment: 'center', backgroundColor: '#559955', bottomColor: '#FFF', needsFullscreen: false, src: 'pineapple.json', topColor: '#FFF' },
  { alignment: 'center', backgroundColor: '#000', bottomColor: '#FFF', needsFullscreen: false, src: 'wave.json', topColor: '#FFF' },
  { alignment: 'center', backgroundColor: '#FFF', bottomColor: '#222', needsFullscreen: false, src: 'donut.json', topColor: '#222' },
  { alignment: 'center', backgroundColor: '#FFF', bottomColor: '#222', needsFullscreen: false, src: 'crow.json', topColor: '#222' },
  { alignment: 'center', backgroundColor: '#aaf7ff', bottomColor: '#222', needsFullscreen: false, src: 'dirigible.json', topColor: '#222' },
  { alignment: 'center', backgroundColor: '#FFF', bottomColor: '#222', needsFullscreen: false, src: 'coffee.json', topColor: '#222' },
  { alignment: 'center', backgroundColor: '#FFF', bottomColor: '#222', needsFullscreen: false, src: 'avocado.json', topColor: '#222' },
  { alignment: 'center', backgroundColor: '#2E2E2E', bottomColor: '#FFF', needsFullscreen: false, src: 'waterfall.json', topColor: '#FFF' },
  { alignment: 'center', backgroundColor: '#000', bottomColor: '#FFF', needsFullscreen: false, src: 'sunshine.json', topColor: '#FFF' },
  { alignment: 'center', backgroundColor: '#FFFFDE', bottomColor: '#222', needsFullscreen: false, src: 'sunrise.json', topColor: '#222' },
  { alignment: 'center', backgroundColor: '#8e555a', bottomColor: '#FFF', needsFullscreen: false, src: 'be_happy.json', topColor: '#FFF' },
  { alignment: 'top', backgroundColor: '#FFD', bottomColor: '#222', needsFullscreen: false, src: 'girl.json', topColor: '#222' },
  { alignment: 'center', bottomColor: '#384F8D', needsFullscreen: true, src: 'night.json', topColor: '#FFF' },
  { alignment: 'center', backgroundColor: '#A5C3DC', bottomColor: '#222', needsFullscreen: true, src: 'seagul.json', topColor: '#222' },
  { alignment: 'top', backgroundColor: '#FFD', bottomColor: '#222', needsFullscreen: false, src: 'swinging.json', topColor: '#222' },
  { alignment: 'center', backgroundColor: '#C56F71', bottomColor: '#FFF', needsFullscreen: false, src: 'coffeegirl.json', topColor: '#FFF' },
  { alignment: 'bottom', backgroundColor: '#E7E9F5', bottomColor: '#FFF', needsFullscreen: true, src: 'montain.json', topColor: '#222' },
  { alignment: 'top', backgroundColor: '#E8C159', bottomColor: '#222', needsFullscreen: true, src: 'seaview.json', topColor: '#FFF' },
  { alignment: 'bottom', backgroundColor: '#C69FC2', bottomColor: '#FFF', needsFullscreen: true, src: 'train.json', topColor: '#FFF' },
  { alignment: 'bottom', bottomColor: '#FFF', needsFullscreen: true, src: 'solar.json', topColor: '#222' },
];
