export type SoundFile = {src: string, title: string, duration?: number, artist?: string, url?: string};

/** An array of all available music files. */
export const MusicFiles: Array<SoundFile & {duration: number}> = [
  { artist: 'Ron Gelinas Chillout Lounge', duration: 223.25, src: 'Acceptance.ogg', title: 'Acceptance', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 210, src: 'All_in_a_Day.ogg', title: 'All in a Day', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 168.5, src: 'Another_Day.ogg', title: 'Another Day', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 158.25, src: 'Aura.ogg', title: 'Aura', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 220.75, src: 'Beacon_Of_Light.ogg', title: 'Beacon Of Light', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 190, src: 'Believe.ogg', title: 'Believe', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 186.5, src: 'Best_Wishes.ogg', title: 'Best Wishes', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 211.25, src: 'Break_Away.ogg', title: 'Break Away', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 127.06, src: 'Campfire.ogg', title: 'Campfire', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 160.41, src: 'Carefree.ogg', title: 'Carefree', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 162.44, src: 'Casual.ogg', title: 'Casual', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 131.71, src: 'Cleansing_Rain.ogg', title: 'Cleansing Rain', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 4.39, src: 'Come.ogg', title: 'Come', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 57.27, src: 'Connecting.ogg', title: 'Connecting', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 2.18, src: 'Contentment.ogg', title: 'Contentment', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 19.59, src: 'Daybreak_Chill_Blend.ogg', title: 'Daybreak Chill Blend', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 27.00, src: 'Defiant.ogg', title: 'Defiant', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 19.20, src: 'Desires.ogg', title: 'Desires', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 11.05, src: 'Drops.ogg', title: 'Drops', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 1 * 60 + 44.68, src: 'Easy.ogg', title: 'Easy', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 57.00, src: 'Edge_Of_Night.ogg', title: 'Edge Of Night', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 53.82, src: 'Elegantly_Disconnected.ogg', title: 'Elegantly Disconnected', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 16.24, src: 'Endeavour.ogg', title: 'Endeavour', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 55.25, src: 'Equanimity.ogg', title: 'Equanimity', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 8.57, src: 'Equatorial_Run.ogg', title: 'Equatorial Run', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 42.00, src: 'Equilibrium.ogg', title: 'Equilibrium', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 2.61, src: 'Equinox.ogg', title: 'Equinox', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 7.50, src: 'Evening_Out.ogg', title: 'Evening Out', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 37.71, src: 'Falling_Leaves.ogg', title: 'Falling Leaves', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 58.96, src: 'Far_Away.ogg', title: 'Far Away', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 39.13, src: 'Feel_It.ogg', title: 'Feel It', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 40.41, src: 'Feeling_Good.ogg', title: 'Feeling Good', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 2.96, src: 'Feeling_Lucky.ogg', title: 'Feeling Lucky', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 44.35, src: 'Fulfilled.ogg', title: 'Fulfilled', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 1.09, src: 'Gaining_Momentum.ogg', title: 'Gaining Momentum', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 6.82, src: 'Get_Over_It.ogg', title: 'Get Over It', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 39.57, src: 'Getting_It_Done.ogg', title: 'Getting It Done', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 47.88, src: 'Hang_Gliding.ogg', title: 'Hang Gliding', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 16.36, src: 'Happy_Place.ogg', title: 'Happy Place', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 4 * 60 + 6.15, src: 'Here.ogg', title: 'Here', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 27.69, src: 'Iced_Tea.ogg', title: 'Iced Tea', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 27.50, src: 'Imminent.ogg', title: 'Imminent', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 35.56, src: 'Island_Hopping.ogg', title: 'Island Hopping', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 33.91, src: 'Island_Life.ogg', title: 'Island Life', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 48.51, src: 'It_Is_What_It_Is.ogg', title: 'It Is What It Is', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 49.09, src: 'Let_It_Go_Now.ogg', title: 'Let It Go Now', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 37.96, src: 'Loyal.ogg', title: 'Loyal', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 2.55, src: 'Midnight_Shuffle.ogg', title: 'Midnight Shuffle', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 16.36, src: 'Mojito.ogg', title: 'Mojito', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 7.59, src: 'Monday_Morning.ogg', title: 'Monday Morning', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 4 * 60 + 5.94, src: 'Natural_High.ogg', title: 'Natural High', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 13.09, src: 'Never_Meant_To_Be.ogg', title: 'Never Meant To Be', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 14.40, src: 'New_Direction_Instrumental.ogg', title: 'New Direction Instrumental', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 34.74, src: 'New_Heights.ogg', title: 'New Heights', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 34.11, src: 'Night_At_The_Beach.ogg', title: 'Night At The Beach', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 50.40, src: 'Over_The_Horizon.ogg', title: 'Over The Horizon', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 25.12, src: 'Peculiar.ogg', title: 'Peculiar', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 35.71, src: 'Ready.ogg', title: 'Ready', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 3.00, src: 'Remember.ogg', title: 'Remember', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 59.08, src: 'Reminiscence.ogg', title: 'Reminiscence', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 40.80, src: 'Resolve_Clean_Guitar.ogg', title: 'Resolve Clean Guitar', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 40.80, src: 'Resolve_Gritty_Guitar.ogg', title: 'Resolve Gritty Guitar', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 19.09, src: 'Simplify.ogg', title: 'Simplify', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 55.61, src: 'Slinky.ogg', title: 'Slinky', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 8.57, src: 'Slow_Grind.ogg', title: 'Slow Grind', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 23.18, src: 'Soul_Searching.ogg', title: 'Soul Searching', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 30.61, src: 'Soulful_Memories.ogg', title: 'Soulful Memories', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 57.50, src: 'Still_Standing.ogg', title: 'Still Standing', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 38.18, src: 'Subtle_Swagger.ogg', title: 'Subtle Swagger', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 46.00, src: 'Summer.ogg', title: 'Summer', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 41.12, src: 'The_Art_of_Healing.ogg', title: 'The Art of Healing', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 37.33, src: 'The_City.ogg', title: 'The City', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 57.14, src: 'Thinking_of_You.ogg', title: 'Thinking of You', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 14.32, src: 'Tropical_Yearnings.ogg', title: 'Tropical Yearnings', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 34.67, src: 'Upside_Quest.ogg', title: 'Upside Quest', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 52.00, src: 'Urgent.ogg', title: 'Urgent', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 4.19, src: 'Voyage.ogg', title: 'Voyage', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 1.28, src: 'Waiting.ogg', title: 'Waiting', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 11.71, src: 'Wandering.ogg', title: 'Wandering', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 12.00, src: 'We_Are_Harmony.ogg', title: 'We Are Harmony', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 5.16, src: 'Where_Will_I_Go_Instrumental.ogg', title: 'Where Will I Go? Instrumental', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 25.00, src: 'Windsurfing.ogg', title: 'Windsurfing', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 51.43, src: 'Winter_Bounce.ogg', title: 'Winter Bounce', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 2 * 60 + 21.33, src: 'You.ogg', title: 'You', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 0.00, src: 'You_Show_Me_Remix.ogg', title: 'You Show Me Remix', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
  { artist: 'Ron Gelinas Chillout Lounge', duration: 3 * 60 + 54.86, src: 'You_Show_Me_feat._Kellie_Allen.ogg', title: 'You Show Me feat. Kellie Allen', url: 'https://soundcloud.com/atmospheric-music-portal/sets/free-download-and-use-in-your' },
];

/** Total duration of the music in seconds */
export const TotalMusicDuration = MusicFiles.reduce((prev, curr) => prev + curr.duration, 0);

export const Sounds: Array<SoundFile> = [
  { src: 'campfire.ogg', title: 'Campfire' },
  { src: 'people_talk_inside.ogg', title: 'People talk inside' },
  { src: 'rain_city.ogg', title: 'Rain City' },
  { src: 'rain_forest.ogg', title: 'Rain Forest' },
  { src: 'river.ogg', title: 'River' },
  { src: 'waves.ogg', title: 'Waves' },
  { src: 'wind.ogg', title: 'Wind' },
];

export type LottieSrc = { src: string, needsFullscreen: boolean, alignment: 'top' | 'center' | 'bottom', controlColor: string, volumesColor: string, backgroundColor?: string };

export const Lotties: Array<LottieSrc> = [
  { alignment: 'center', backgroundColor: '#111', controlColor: '#FFF', needsFullscreen: false, src: 'mushroom.json', volumesColor: '#FFF' },
  { alignment: 'center', backgroundColor: '#000', controlColor: '#FFF', needsFullscreen: false, src: 'l1.json', volumesColor: '#FFF' },
  { alignment: 'center', backgroundColor: '#65f0f7', controlColor: '#222', needsFullscreen: false, src: 'turtle.json', volumesColor: '#222' },
  { alignment: 'center', backgroundColor: '#FFF', controlColor: '#222', needsFullscreen: false, src: 'donut.json', volumesColor: '#222' },
  { alignment: 'center', backgroundColor: '#FFF', controlColor: '#222', needsFullscreen: false, src: 'crow.json', volumesColor: '#222' },
  { alignment: 'center', backgroundColor: '#aaf7ff', controlColor: '#222', needsFullscreen: false, src: 'dirigible.json', volumesColor: '#222' },
  { alignment: 'center', backgroundColor: '#FFF', controlColor: '#222', needsFullscreen: false, src: 'coffee.json', volumesColor: '#222' },
  { alignment: 'center', backgroundColor: '#FFF', controlColor: '#222', needsFullscreen: false, src: 'avocado.json', volumesColor: '#222' },
  { alignment: 'center', backgroundColor: '#2E2E2E', controlColor: '#FFF', needsFullscreen: false, src: 'waterfall.json', volumesColor: '#FFF' },
  { alignment: 'center', backgroundColor: '#000', controlColor: '#FFF', needsFullscreen: false, src: 'sunshine.json', volumesColor: '#FFF' },
  { alignment: 'center', backgroundColor: '#FFFFDE', controlColor: '#222', needsFullscreen: false, src: 'sunrise.json', volumesColor: '#222' },
  { alignment: 'center', backgroundColor: '#8e555a', controlColor: '#FFF', needsFullscreen: false, src: 'be_happy.json', volumesColor: '#FFF' },
  { alignment: 'top', backgroundColor: '#FFD', controlColor: '#222', needsFullscreen: false, src: 'girl.json', volumesColor: '#222' },
  { alignment: 'center', controlColor: '#384F8D', needsFullscreen: true, src: 'night.json', volumesColor: '#FFF' },
  { alignment: 'center', backgroundColor: '#A5C3DC', controlColor: '#222', needsFullscreen: true, src: 'seagul.json', volumesColor: '#222' },
  { alignment: 'top', backgroundColor: '#FFD', controlColor: '#222', needsFullscreen: false, src: 'swinging.json', volumesColor: '#222' },
  { alignment: 'center', backgroundColor: '#C56F71', controlColor: '#FFF', needsFullscreen: false, src: 'coffeegirl.json', volumesColor: '#FFF' },
  { alignment: 'bottom', backgroundColor: '#E7E9F5', controlColor: '#FFF', needsFullscreen: true, src: 'montain.json', volumesColor: '#222' },
  { alignment: 'top', backgroundColor: '#E8C159', controlColor: '#222', needsFullscreen: true, src: 'seaview.json', volumesColor: '#FFF' },
  { alignment: 'bottom', backgroundColor: '#C69FC2', controlColor: '#FFF', needsFullscreen: true, src: 'train.json', volumesColor: '#FFF' },
  { alignment: 'bottom', controlColor: '#FFF', needsFullscreen: true, src: 'solar.json', volumesColor: '#222' },
];
